{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "2d05df53",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "import pyperclip\n",
    "import pyshorteners\n",
    "\n",
    "def shorten_url():\n",
    "    long_url = entry_long_url.get()\n",
    "    if long_url and long_url != 'Enter URL here...':\n",
    "        try:\n",
    "            short_url = shortener.tinyurl.short(long_url)\n",
    "            entry_short_url.config(state=tk.NORMAL)\n",
    "            entry_short_url.delete(0, tk.END)\n",
    "            entry_short_url.insert(0, short_url)\n",
    "            copy_button.config(state=tk.NORMAL)\n",
    "            entry_short_url.config(state='readonly')\n",
    "        except Exception as e:\n",
    "            entry_short_url.config(state=tk.NORMAL)\n",
    "            entry_short_url.delete(0, tk.END)\n",
    "            entry_short_url.insert(0, f\"Error: {str(e)}\")\n",
    "            entry_short_url.config(state='readonly')\n",
    "    else:\n",
    "        entry_short_url.config(state=tk.NORMAL)\n",
    "        entry_short_url.delete(0, tk.END)\n",
    "        copy_button.config(state=tk.DISABLED)\n",
    "        entry_short_url.config(state='readonly')\n",
    "\n",
    "def copy_to_clipboard():\n",
    "    short_url = entry_short_url.get()\n",
    "    pyperclip.copy(short_url)\n",
    "\n",
    "def on_entry_click(event):\n",
    "    if entry_long_url.get() == 'Enter URL here...':\n",
    "        entry_long_url.delete(0, tk.END)\n",
    "        entry_long_url.config(fg='black')\n",
    "\n",
    "def on_focusout(event):\n",
    "    if entry_long_url.get() == '':\n",
    "        entry_long_url.insert(0, 'Enter URL here...')\n",
    "        entry_long_url.config(fg='grey')\n",
    "\n",
    "root = tk.Tk()\n",
    "root.title(\"URL Shortener\")\n",
    "root.geometry(\"500x300\")\n",
    "root.configure(bg=\"white\")\n",
    "\n",
    "heading = tk.Label(root, text=\"URL SHORTENER\", font=(\"Arial\", 27, \"bold\"), bg=\"white\", fg=\"green\")\n",
    "heading.grid(row=0, column=0, columnspan=3, pady=10)\n",
    "\n",
    "sub_heading = tk.Label(root, text=\"Paste your URL here\", font=(\"Arial\", 18), bg=\"white\", fg=\"black\")\n",
    "sub_heading.grid(row=1, column=0, columnspan=3, pady=5)\n",
    "\n",
    "entry_long_url = tk.Entry(root, width=40, fg='grey')\n",
    "entry_long_url.insert(0, 'Enter URL here...')\n",
    "entry_long_url.bind('<FocusIn>', on_entry_click)\n",
    "entry_long_url.bind('<FocusOut>', on_focusout)\n",
    "entry_long_url.grid(row=2, column=1, padx=10, pady=10)\n",
    "\n",
    "shortener = pyshorteners.Shortener()\n",
    "\n",
    "shorten_button = tk.Button(root, text=\"Shorten\", command=shorten_url, bg=\"green\", fg=\"white\")\n",
    "shorten_button.grid(row=2, column=2, padx=10, pady=10)\n",
    "\n",
    "label_short_url = tk.Label(root, text=\"Shortened URL:\", bg=\"white\")\n",
    "label_short_url.grid(row=3, column=0, padx=10, pady=10)\n",
    "\n",
    "entry_short_url = tk.Entry(root, width=40, state='readonly')\n",
    "entry_short_url.grid(row=3, column=1, padx=10, pady=10)\n",
    "\n",
    "copy_button = tk.Button(root, text=\"Copy URL\", command=copy_to_clipboard, state=tk.DISABLED)\n",
    "copy_button.grid(row=3, column=2, padx=10, pady=10)\n",
    "\n",
    "label_purpose = tk.Label(root, text=\"This tool shortens long URLs into shorter ones.\", font=(\"Arial\", 14), bg=\"white\", fg=\"green\")\n",
    "label_purpose.grid(row=4, column=0, columnspan=3, padx=10, pady=10)\n",
    "\n",
    "root.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2611d785",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
